services:
  postgres-server:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka-server:
    image: apache/kafka:latest
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
      KAFKA_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5

  init-kafka:
    image: apache/kafka:latest
    container_name: init-kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Creating kafka topics...'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-server:29092 --create --if-not-exists --topic transfer-created --partitions 1 --replication-factor 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-server:29092 --create --if-not-exists --topic transfer-completed --partitions 1 --replication-factor 1
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-server:29092 --create --if-not-exists --topic transfer-failed --partitions 1 --replication-factor 1
      
      echo -e 'Successfully created topics:'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka-server:29092 --list
      "
    depends_on:
      kafka-server:
        condition: service_healthy

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./observability/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      tempo:
        condition: service_started
      loki:
        condition: service_started
      prometheus:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observability/tempo.yml:/etc/tempo.yaml
    ports:
      - "3200:3200"

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: [ "-config.file=/etc/loki/loki.yml" ]
    ports:
      - "3100:3100"
    volumes:
      - ./observability/loki.yml:/etc/loki/loki.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      otel-collector:
        condition: service_started
  
  account-service:
    build:
      context: .
      dockerfile: Services/AccountService/AccountService.API/Dockerfile
    container_name: account-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "5001:8080"
    depends_on:
      postgres-server:
        condition: service_healthy
      redis-server:
        condition: service_healthy
      kafka-server:
        condition: service_healthy
      otel-collector:
        condition: service_started

  fraud-detection-service:
    build:
      context: .
      dockerfile: Services/FraudDetectionService/FraudDetectionService.API/Dockerfile
    container_name: fraud-detection-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "5002:8080"
    depends_on:
      otel-collector:
        condition: service_started

  ledger-service:
    build:
      context: .
      dockerfile: Services/LedgerService/LedgerService.API/Dockerfile
    container_name: ledger-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "5003:8080"
    depends_on:
      postgres-server:
        condition: service_healthy
      kafka-server:
        condition: service_healthy
      otel-collector:
        condition: service_started

  notification-service:
    build:
      context: .
      dockerfile: Services/NotificationService/NotificationService.API/Dockerfile
    container_name: notification-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "5004:8080"
    depends_on:
      postgres-server:
        condition: service_healthy
      kafka-server:
        condition: service_healthy
      otel-collector:
        condition: service_started

  transaction-service:
    build:
      context: .
      dockerfile: Services/TransactionService/TransactionService.API/Dockerfile
    container_name: transaction-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    ports:
      - "5005:8080"
    depends_on:
      postgres-server:
        condition: service_started
      kafka-server:
        condition: service_started
      account-service:
        condition: service_started
      fraud-detection-service:
        condition: service_started
      otel-collector:
        condition: service_started

volumes:
  postgres_data: